apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  namespace: guests
  description: Platform Team
spec:
  type: team
  profile:
    displayName: Platform Team
  children: []
